# Generated by Django 5.0.14 on 2026-10-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(choices=[('user', 'Colaborador'), ('bot', 'Agente Virtual')], max_length=10)),
                ('texto', models.TextField()),
                ('tipo_accion', models.CharField(blank=True, default='INFO_GENERAL', max_length=50)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='hr_services.empleado')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
