# Generated by Django 5.0.14 on 2026-09-24 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConocimientoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Políticas Generales', max_length=100)),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleado', models.CharField(max_length=20, unique=True, verbose_name='Número de Empleado')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('departamento', models.CharField(default='Tecnología de la Información', max_length=100)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_vacaciones_totales', models.PositiveIntegerField(default=12)),
                ('dias_vacaciones_tomados', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirigido_a', models.CharField(default='A quien corresponda', max_length=200)),
                ('incluir_sueldo', models.BooleanField(default=False)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='constancias/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constancias', to='hr_services.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to='hr_services.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=30, unique=True)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('respuesta_rh', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='hr_services.empleado')),
            ],
        ),
    ]
