# Generated by Django 5.0.14 on 2026-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Foto de Perfil'),
        ),
    ]
